Blogifier.Core/Controllers/ContentController.cs
using Blogifier.Core.Common;
using Blogifier.Core.Data.Domain;
using Blogifier.Core.Data.Interfaces;
using Blogifier.Core.Data.Models;
using Blogifier.Core.Middleware;
using Blogifier.Core.Services.Search;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blogifier.Core.Controllers
{
    [Authorize]
    [Route("admin/[controller]")]
    public class ContentController : Controller
	{
		private readonly string _theme;
        IUnitOfWork _db;
        ISearchService _search;

		public ContentController(IUnitOfWork db, ISearchService search)
		{
			_db = db;
            _search = search;
			_theme = $"~/{ApplicationSettings.BlogAdminFolder}/Content/";
		}

        [VerifyProfile]
        [HttpGet]
        public async Task<IActionResult> Index(int page = 1, string user = "0", string status = "A", string cats = "", string search = "")
		{
            var profile = GetProfile();
           
            var fields = await _db.CustomFields.GetCustomFields(CustomType.Profile, profile.Id);
            var pageSize = BlogSettings.ItemsPerPage;

            if (fields.ContainsKey(Constants.PostListSize))
                pageSize = int.Parse(fields[Constants.PostListSize]);

            var pager = new Pager(page, pageSize);        
            var model = new AdminPostsModel { Profile = profile };

            model.CustomFields = fields;

            if (model.Profile.IsAdmin)
                model.Users = _db.Profiles.Find(p => p.IdentityName != model.Profile.IdentityName);

            var userProfile = model.Profile;
            if (user != "0" && profile.IsAdmin)
                userProfile = _db.Profiles.Single(p => p.Id == int.Parse(user));

            model.StatusFilter = GetStatusFilter(status);

            var selectedCategories = new List<string>();
            var dbCategories = new List<Category>();
            model.CategoryFilter = _db.Categories.CategoryList(c => c.ProfileId == userProfile.Id).ToList();
            if (!string.IsNullOrEmpty(cats))
            {
                selectedCategories = cats.Split(',').ToList();
                foreach (var ftr in model.CategoryFilter)
                {
                    if (selectedCategories.Contains(ftr.Value))
                    {
                        ftr.Selected = true;
                    }
                }
            }

            if (string.IsNullOrEmpty(search))
            {
                model.BlogPosts = _db.BlogPosts.ByFilter(status, selectedCategories, userProfile.Slug, pager).Result;
            }
            else
            {
                model.BlogPosts = _search.Find(pager, search, userProfile.Slug).Result;
            }
            
            model.Pager = pager;

            var anyPost = _db.BlogPosts.Find(p => p.ProfileId == userProfile.Id).FirstOrDefault();
            ViewBag.IsFirstPost = anyPost == null;

            return View(_theme + "Index.cshtml", model);
        }

        [VerifyProfile]
        [Route("editor/{id:int}")]
        public IActionResult Editor(int id, string user = "0")
        {
            var profile = GetProfile();
            var userProfile = profile;

            if (user != "0")
            {
                userProfile = _db.Profiles.Single(p => p.Id == int.Parse(user));
            }

            var post = new BlogPost();
            var categories = _db.Categories.CategoryList(c => c.ProfileId == userProfile.Id).ToList();

            if (id > 0)
            {
                if (profile.IsAdmin)
                {
                    post = _db.BlogPosts.SingleIncluded(p => p.Id == id).Result;
                }
                else
                {
                    post = _db.BlogPosts.SingleIncluded(p => p.Id == id && p.Profile.Id == profile.Id).Result;
                }
            }

            if(post.PostCategories != null)
            {
                foreach (var pc in post.PostCategories)
                {
                    foreach (var cat in categories)
                    {
                        if (pc.CategoryId.ToString() == cat.Value)
                        {
                            cat.Selected = true;
                        }
                    }
                }
            }

            var model = new AdminEditorModel { Profile = profile, CategoryList = categories, BlogPost = post };
            return View(_theme + "Editor.cshtml", model);
        }

        private Profile GetProfile()
        {
            return _db.Profiles.Single(b => b.IdentityName == User.Identity.Name);
        }

        List<SelectListItem> GetStatusFilter(string filter)
        {
            return new List<SelectListItem>
            {
                new SelectListItem { Text = "All", Value = "A", Selected = filter == "A" },
                new SelectListItem { Text = "Drafts", Value = "D", Selected = filter == "D" },
                new SelectListItem { Text = "Published", Value = "P", Selected = filter == "P" }
            };
        }
    }
}

Blogifier.Core/Controllers/PackagesController.cs
using Blogifier.Core.Common;
using Blogifier.Core.Data.Domain;
using Blogifier.Core.Data.Interfaces;
using Blogifier.Core.Data.Models;
using Blogifier.Core.Middleware;
using Blogifier.Core.Services.Packages;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Blogifier.Core.Controllers
{
    [Authorize]
    [Route("admin/[controller]")]
    public class PackagesController : Controller
	{
		private readonly string _theme;
        IUnitOfWork _db;
        IPackageService _pkgs;

		public PackagesController(IUnitOfWork db, IPackageService pkgs)
		{
			_db = db;
            _pkgs = pkgs;
			_theme = $"~/{ApplicationSettings.BlogAdminFolder}/";
		}

        [VerifyProfile]
        [HttpGet("widgets")]
        public async Task<IActionResult> Widgets()
        {
            var model = new AdminPackagesModel {
                Profile = GetProfile(),
                Packages = await _pkgs.Find(PackageType.Widgets)
            };
            return View($"{_theme}Packages/Widgets.cshtml", model);
        }

        [VerifyProfile]
        [HttpGet("themes")]
        public IActionResult Themes()
        {
            var model = new AdminPackagesModel { Profile = GetProfile() };
            model.Packages = new List<PackageListItem>();

            return View($"{_theme}Packages/Themes.cshtml", model);
        }

        private Profile GetProfile()
        {
            return _db.Profiles.Single(b => b.IdentityName == User.Identity.Name);
        }
    }
}

Blogifier.Core/Controllers/SettingsController.cs
using Blogifier.Core.Common;
using Blogifier.Core.Data.Domain;
using Blogifier.Core.Data.Interfaces;
using Blogifier.Core.Data.Models;
using Blogifier.Core.Extensions;
using Blogifier.Core.Middleware;
using Blogifier.Core.Services.FileSystem;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;

namespace Blogifier.Core.Controllers
{
    [Authorize]
    [Route("admin/[controller]")]
	public class SettingsController : Controller
	{
		IUnitOfWork _db;
        ILogger _logger;
        string _theme;

		public SettingsController(IUnitOfWork db, ILogger<SettingsController> logger)
		{
			_db = db;
            _logger = logger;
            _theme = $"~/{ApplicationSettings.BlogAdminFolder}/Settings/";
        }

        [Route("profile")]
        public IActionResult Profile()
        {
            var model = new SettingsProfile();
            model.Profile = GetProfile();
            
            if(model.Profile != null)
            {
                model.AuthorName = model.Profile.AuthorName;
                model.AuthorEmail = model.Profile.AuthorEmail;
                model.Avatar = model.Profile.Avatar;
                model.EmailEnabled = _db.CustomFields.GetValue(CustomType.Application, 0, Constants.SendGridApiKey).Length > 0;
                model.CustomFields = _db.CustomFields.GetUserFields(model.Profile.Id).Result;
            }
            return View(_theme + "Profile.cshtml", model);
        }

        [HttpPost]
        [Route("profile")]
        public IActionResult Profile(SettingsProfile model)
        {
            var profile = GetProfile();
            if (ModelState.IsValid)
            {
                if (profile == null)
                {
                    profile = new Profile();

                    if (_db.Profiles.All().ToList().Count == 0)
                    {
                        profile.IsAdmin = true;
                    }
                    profile.AuthorName = model.AuthorName;
                    profile.AuthorEmail = model.AuthorEmail;
                    profile.Avatar = model.Avatar;

                    profile.IdentityName = User.Identity.Name;
                    profile.Slug = SlugFromTitle(profile.AuthorName);
                    profile.Title = BlogSettings.Title;
                    profile.Description = BlogSettings.Description;
                    profile.BlogTheme = BlogSettings.Theme;

                    _db.Profiles.Add(profile);
                }
                else
                {
                    profile.AuthorName = model.AuthorName;
                    profile.AuthorEmail = model.AuthorEmail;
                    profile.Avatar = model.Avatar;
                }
                _db.Complete();

                model.Profile = GetProfile();

                // save custom fields
                if(profile.Id > 0 && model.CustomFields != null)
                {
                    SaveCustomFields(model.CustomFields, profile.Id);
                }
                model.CustomFields = _db.CustomFields.GetUserFields(model.Profile.Id).Result;

                ViewBag.Message = "Profile updated";
            }
            return View(_theme + "Profile.cshtml", model);
        }

        [VerifyProfile]
        [Route("about")]
        public IActionResult About()
        {
            return View(_theme + "About.cshtml", new AdminBaseModel { Profile = GetProfile() });
        }

        [MustBeAdmin]
        [Route("general")]
        public IActionResult General()
        {
            var profile = GetProfile();
            var storage = new BlogStorage("");

            var model = new SettingsGeneral
            {
                Profile = profile,
                BlogThemes = BlogSettings.BlogThemes,
                Title = BlogSettings.Title,
                Description = BlogSettings.Description,
                BlogTheme = BlogSettings.Theme,
                Logo = BlogSettings.Logo,
                Avatar = ApplicationSettings.ProfileAvatar,
                Image = BlogSettings.Cover,
                EmailKey = _db.CustomFields.GetValue(CustomType.Application, 0, Constants.SendGridApiKey),
                BlogHead = _db.CustomFields.GetValue(CustomType.Application, 0, Constants.HeadCode),
                BlogFooter = _db.CustomFields.GetValue(CustomType.Application, 0, Constants.FooterCode)
            };
            return View(_theme + "General.cshtml", model);
        }

        [HttpPost]
        [MustBeAdmin]
        [Route("general")]
        public IActionResult General(SettingsGeneral model)
        {
            var storage = new BlogStorage("");
            model.BlogThemes = BlogSettings.BlogThemes;
            model.Profile = GetProfile();

            if (ModelState.IsValid)
            {
                BlogSettings.Title = model.Title;
                BlogSettings.Description = model.Description;
                BlogSettings.Logo = model.Logo;
                ApplicationSettings.ProfileAvatar = model.Avatar;
                BlogSettings.Cover = model.Image;
                BlogSettings.Theme = model.BlogTheme;

                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.Title, model.Title);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.Description, model.Description);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.ProfileLogo, model.Logo);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.ProfileAvatar, model.Avatar);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.ProfileImage, model.Image);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.BlogTheme, model.BlogTheme);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.SendGridApiKey, model.EmailKey);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.HeadCode, model.BlogHead);
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.FooterCode, model.BlogFooter);

                model.Profile.BlogTheme = model.BlogTheme;

                _db.Complete();

                ViewBag.Message = "Updated";
            }
            return View(_theme + "General.cshtml", model);
        }

        [MustBeAdmin]
        [Route("posts")]
        public IActionResult Posts()
        {
            var profile = GetProfile();

            var model = new SettingsPosts
            {
                Profile = profile,
                PostImage = BlogSettings.Cover,
                PostFooter = _db.CustomFields.GetValue(CustomType.Application, 0, Constants.PostCode),
                ItemsPerPage = BlogSettings.ItemsPerPage
            };
            return View(_theme + "Posts.cshtml", model);
        }

        [HttpPost]
        [MustBeAdmin]
        [Route("posts")]
        public IActionResult Posts(SettingsPosts model)
        {
            model.Profile = GetProfile();

            if (ModelState.IsValid)
            {
                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.ItemsPerPage, model.ItemsPerPage.ToString());
                BlogSettings.ItemsPerPage = model.ItemsPerPage;

                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.PostImage, model.PostImage);
                BlogSettings.PostCover = model.PostImage;

                _db.CustomFields.SetCustomField(CustomType.Application, 0, Constants.PostCode, model.PostFooter);

                _db.Complete();

                ViewBag.Message = "Updated";
            }
            return View(_theme + "Posts.cshtml", model);
        }

        [MustBeAdmin]
        [Route("advanced")]
        public IActionResult Advanced()
        {
            var profile = GetProfile();

            var model = new SettingsAdvanced
            {
                Profile = profile
            };
            return View(_theme + "Advanced.cshtml", model);
        }

        Profile GetProfile()
        {
            return _db.Profiles.Single(p => p.IdentityName == User.Identity.Name);
        }

        void SaveCustomFields(Dictionary<string, string> fields, int profileId)
        {
            if(fields != null && fields.Count > 0)
            {
                foreach (var field in fields)
                {
                    _db.CustomFields.SetCustomField(CustomType.Profile, profileId, field.Key, field.Value);
                }
            }
        }

        string SlugFromTitle(string title)
        {
            var slug = title.ToSlug();
            if (_db.Profiles.Single(b => b.Slug == slug) != null)
            {
                for (int i = 2; i < 100; i++)
                {
                    if (_db.Profiles.Single(b => b.Slug == slug + i.ToString()) == null)
                    {
                        return slug + i.ToString();
                    }
                }
            }
            return slug;
        }
    }
}

Blogifier.Core/Views/Embedded/Admin/_Shared/_FileManager.cshtml
<div class="modal fade bf-filemanager" id="fileManager" tabindex="-1" role="dialog" aria-labelledby="fileManagerLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-header d-flex">
                    <label class="custom-control custom-checkbox my-auto pr-0 mr-2">
                        <input type="checkbox" class="custom-control-input item-check">
                        <span class="custom-control-indicator"></span>
                    </label>
                    <button class="btn btn-primary btn-sm btn-rounded mr-2" type="button" onclick="return fileManagerController.uploadClick()">upload</button>
                    <button id="btnDelete" class="btn btn-outline-secondary btn-icon btn-rounded btn-sm mr-2" type="button" data-placement="bottom" data-tooltip title="Delete" onclick="return fileManagerController.remove()"><i class="fa fa-trash"></i></button>
                    <div class="loading loading-white loading-sm"><div class="loading-dot-1"></div><div class="loading-dot-2"></div><div class="loading-dot-3"></div></div>
                    <div class="dropdown ml-auto">
                        <button class="btn btn-outline-secondary btn-icon btn-rounded btn-sm" type="button" data-placement="bottom" data-tooltip title="Filters" id="filterFileManager" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-filter"></i></button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterFileManager">
                            <form class="bf-filemanager-search" action="" method="get">
                                <input type="search" id="search" name="search" class="form-control" placeholder="Search..." />
                            </form>
                            <label class="custom-control custom-radio d-block">
                                <input id="filterAll" value="filterAll" name="filter" type="radio" checked class="custom-control-input" onchange="return fileManagerController.load(1)">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">All</span>
                            </label>
                            <label class="custom-control custom-radio d-block">
                                <input id="filterImages" value="filterImages" name="filter" type="radio" class="custom-control-input" onchange="return fileManagerController.load(1)">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">Images</span>
                            </label>
                            <label class="custom-control custom-radio d-block">
                                <input id="filterAttachments" value="filterAttachments" name="filter" type="radio" class="custom-control-input" onchange="return fileManagerController.load(1)">
                                <span class="custom-control-indicator"></span>
                                <span class="custom-control-description">Attachments</span>
                            </label>
                        </div>
                    </div>
                    <button type="button" class="close ml-2" title="Close" data-placement="bottom" data-tooltip data-dismiss="modal" aria-label="Close">
                        <i class="fa fa-times"></i>
                    </button>
                </div>
                <div class="bf-filemanager-body">
                    <div id="fileManagerList" class="row no-gutters"></div>
                </div>
            </div>
            <div class="modal-footer d-flex">
                <div id="file-pagination" class="file-pagination" role="group"></div>
                <button class="btn btn-link btn-sm btn-rounded ml-auto" type="button" data-dismiss="modal">cancel</button>
                <button id="btnSelect" class="btn btn-primary btn-sm btn-rounded" type="button" onclick="return fileManagerController.pick(0)">select</button>
            </div>
        </div>
    </div>
</div>
<div style="display:none;">
    <form method="post" name="frmUpload" id="frmUpload" asp-action="Index" asp-controller="Blogifier/Api/Assets/Multiple" enctype="multipart/form-data">
        <input type="file" name="files" id="files" multiple onchange="fileManagerController.uploadSubmit(); return false;" />
        <input type="submit" value="Upload Multiple" />
    </form>
</div>

Blogifier.Core/Views/Embedded/Admin/_Shared/_Foot.cshtml
@using Blogifier.Core.Common
<form method="post" id="frmLogOut" asp-controller="Account" asp-action="Logout" asp-antiforgery="true"></form>
<script src="~/embedded/admin/js/lib/jquery.min.js"></script>
<script src="~/embedded/admin/js/lib/toastr.min.js"></script>
<script src="~/embedded/admin/js/lib/popper.min.js"></script>
<script src="~/embedded/admin/js/lib/bootstrap.min.js"></script>
<script src="~/embedded/admin/js/app/app.js"></script>
<script src="~/embedded/admin/js/app/dataService.js"></script>
<script src="~/embedded/admin/js/app/uploadController.js"></script>
<script>
    var webRoot = '@Url.Content("~/")';
    var blogRoute = '@ApplicationSettings.BlogRoute';
    function getUrl(str) {
        return webRoot + str;
    };
</script>

Blogifier.Core/Views/Embedded/Admin/_Shared/_Head.cshtml
@using Blogifier.Core.Common
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Blogifier - @ViewData["Title"]</title>
<link href="~/embedded/admin/css/bootstrap.min.css" rel="stylesheet">
<link href="~/embedded/admin/css/fontawesome.min.css" rel="stylesheet">
<link href="~/embedded/admin/css/styles.min.css" rel="stylesheet" asp-append-version="true">
<link href="~/embedded/lib/img/favicon.ico" rel="shortcut icon">
</head>

Blogifier.Core/Views/Embedded/Admin/_Shared/_Taskbar.cshtml
@using Blogifier.Core.Common
@{
    var avatar = ApplicationSettings.ProfileAvatar;
    var userName = "";
    var blogTitle = BlogSettings.Title;
    var blogDesc = BlogSettings.Description;
    var blogImg = BlogSettings.Cover;
    if (Model.Profile != null)
    {
        userName = Model.Profile.AuthorName;
        blogTitle = Model.Profile.Title;
        blogDesc = Model.Profile.Description;
        blogImg = string.IsNullOrEmpty(Model.Profile.Image) ? blogImg : Model.Profile.Image;
        if (!string.IsNullOrEmpty(Model.Profile.Avatar))
        {
            avatar = Model.Profile.Avatar;
        }
    }
}
<ul class="bf-taskbar d-flex flex-lg-column">
    <li class="taskbar-item">
        <a class="taskbar-item-link" href="~/admin/content/editor/0" title="New Post">
            <i class="taskbar-item-icon fa fa-plus"></i>
        </a>
    </li>
    <li is-active-route asp-controller="Content" class="taskbar-item">
        <a asp-controller="Content" asp-action="Index" class="taskbar-item-link" title="Posts">
            <i class="taskbar-item-icon fa fa-align-left"></i>
        </a>
    </li>
    @if (Model.Profile.IsAdmin)
    {
        <li is-active-route asp-controller="Packages" class="taskbar-item">
            <a asp-controller="Packages" asp-action="Widgets" class="taskbar-item-link" title="Packages">
                <i class="taskbar-item-icon fa fa-cube"></i>
            </a>
        </li>
        <li is-active-route asp-controller="Settings" class="taskbar-item">
            <a asp-controller="Settings" asp-action="General" class="taskbar-item-link" title="Settings">
                <i class="taskbar-item-icon fa fa-gear"></i>
            </a>
        </li>
    }
    else
    {
        <li is-active-route asp-controller="Settings" class="taskbar-item">
            <a asp-controller="Settings" asp-action="Profile" class="taskbar-item-link" title="Settings">
                <i class="taskbar-item-icon fa fa-gear"></i>
            </a>
        </li>
    }
    <li class="taskbar-item ml-auto ml-lg-0 mt-lg-auto">
        <a class="taskbar-item-link" href="~/" return false;" title="Visit Blog" target="_blank"><i class="taskbar-item-icon fa fa-globe"></i></a>
    </li>
    <li class="taskbar-item">
        <a class="taskbar-item-link" onclick="profileLogOut(); return false;" title="Sign out"><i class="taskbar-item-icon fa fa-sign-out"></i></a>
    </li>
</ul>